import { StyleSheet } from 'react-native';

export const colors = {
  bg: '#000000',
  surface: '#111111',
  surface2: '#1a1a1a',
  border: '#1e1e1e',
  border2: '#2a2a2a',
  border3: '#333333',
  white: '#ffffff',
  gray1: '#888888',
  gray2: '#666666',
  gray3: '#555555',
  gray4: '#444444',
  red: '#ef4444',
};

export const s = StyleSheet.create({
  // --- LAYOUT ---
  flex1: { flex: 1 },
  row: { flexDirection: 'row', alignItems: 'center' },
  center: { alignItems: 'center', justifyContent: 'center' },
  screenBg: { flex: 1, backgroundColor: '#000000' },

  // --- AUTH ---
  authWrap: { flex: 1, backgroundColor: '#000000', justifyContent: 'center', padding: 24 },
  authLogo: { fontSize: 48, textAlign: 'center', marginBottom: 8 },
  authTitle: { fontSize: 28, fontWeight: '900', color: '#ffffff', textAlign: 'center', marginBottom: 4 },
  authSub: { fontSize: 14, color: '#888888', textAlign: 'center', marginBottom: 24, lineHeight: 20 },
  authStatsRow: { flexDirection: 'row', justifyContent: 'center', gap: 24, marginBottom: 32 },
  authStatNum: { fontSize: 22, fontWeight: '900', color: '#ffffff', textAlign: 'center' },
  authStatLabel: { fontSize: 11, color: '#666666', textAlign: 'center', textTransform: 'uppercase', letterSpacing: 1 },
  authInput: { backgroundColor: '#111111', borderWidth: 1, borderColor: '#333333', borderRadius: 8, color: '#ffffff', fontSize: 15, padding: 14, marginBottom: 10 },
  authBtn: { backgroundColor: '#ffffff', borderRadius: 24, padding: 14, alignItems: 'center', marginTop: 4 },
  authBtnText: { color: '#000000', fontWeight: '700', fontSize: 15 },
  authGoogleBtn: { backgroundColor: '#ffffff', borderRadius: 24, padding: 13, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 8, marginBottom: 10 },
  authGoogleText: { color: '#000000', fontWeight: '700', fontSize: 15 },
  authDividerRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginVertical: 6 },
  authDividerLine: { flex: 1, height: 1, backgroundColor: '#222222' },
  authDividerText: { color: '#444444', fontSize: 13 },
  authForgot: { textAlign: 'center', color: '#888888', fontSize: 14, marginTop: 4, textDecorationLine: 'underline' },
  authSwitch: { textAlign: 'center', color: '#666666', fontSize: 14, marginTop: 4 },
  authSwitchLink: { color: '#ffffff', fontWeight: '700', textDecorationLine: 'underline' },

  // --- NAVBAR ---
  navbar: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#0a0a0a', borderBottomWidth: 1, borderBottomColor: '#1e1e1e', padding: 10, paddingHorizontal: 14, gap: 10 },
  navLogo: { fontSize: 16, fontWeight: '900', color: '#ffffff' },
  navSearchBox: { flex: 1, flexDirection: 'row', alignItems: 'center', backgroundColor: '#111111', borderWidth: 1, borderColor: '#2a2a2a', borderRadius: 24, paddingHorizontal: 12, height: 36 },
  navSearchInput: { flex: 1, color: '#ffffff', fontSize: 13, paddingVertical: 0 },
  navActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  createBtn: { backgroundColor: '#ffffff', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 7 },
  createBtnText: { color: '#000000', fontWeight: '700', fontSize: 12 },
  notifBtn: { width: 36, height: 36, borderRadius: 18, borderWidth: 1, borderColor: '#2a2a2a', alignItems: 'center', justifyContent: 'center' },
  notifBadge: { position: 'absolute', top: -4, right: -4, backgroundColor: '#ef4444', width: 16, height: 16, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  notifBadgeText: { color: '#fff', fontSize: 9, fontWeight: '700' },
  avatar: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#ffffff', alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: '#000000', fontWeight: '900', fontSize: 15 },

  // --- BOTTOM TAB (replaces left sidebar) ---
  bottomTab: { flexDirection: 'row', backgroundColor: '#0a0a0a', borderTopWidth: 1, borderTopColor: '#1e1e1e', paddingBottom: 8, paddingTop: 8 },
  tabItem: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 2 },
  tabIcon: { fontSize: 20 },
  tabLabel: { fontSize: 10, color: '#888888' },
  tabLabelActive: { fontSize: 10, color: '#ffffff', fontWeight: '700' },

  // --- GAME CARD ---
  card: { flexDirection: 'row', gap: 12, backgroundColor: '#111111', borderWidth: 1, borderColor: '#1e1e1e', borderRadius: 12, padding: 14, marginBottom: 10 },
  cardVote: { alignItems: 'center', gap: 4, minWidth: 36 },
  voteBtn: { width: 34, height: 34, borderRadius: 6, borderWidth: 1, borderColor: '#2a2a2a', alignItems: 'center', justifyContent: 'center' },
  voteBtnActive: { backgroundColor: '#ffffff', borderColor: '#ffffff' },
  voteBtnText: { color: '#888888', fontSize: 14 },
  voteBtnTextActive: { color: '#000000' },
  voteCount: { fontSize: 13, fontWeight: '700', color: '#ffffff' },
  cardThumb: { width: 64, height: 64, backgroundColor: '#1a1a1a', borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  cardThumbText: { fontSize: 36 },
  cardInfo: { flex: 1 },
  cardTop: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 4 },
  cardDev: { fontSize: 12, color: '#666666' },
  cardStatus: { fontSize: 10, fontWeight: '700', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 20, color: '#000000' },
  cardTitle: { fontSize: 16, fontWeight: '800', color: '#ffffff', marginBottom: 4 },
  cardDesc: { fontSize: 13, color: '#888888', lineHeight: 18, marginBottom: 6 },
  tagsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginBottom: 6 },
  tag: { backgroundColor: '#1a1a1a', borderWidth: 1, borderColor: '#2a2a2a', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 20 },
  tagText: { color: '#888888', fontSize: 11 },
  cardFooter: { flexDirection: 'row', gap: 4, flexWrap: 'wrap' },
  cardAction: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 6 },
  cardActionText: { color: '#555555', fontSize: 12 },

  // --- FILTERS ---
  filterWrap: { backgroundColor: '#111111', borderWidth: 1, borderColor: '#222222', borderRadius: 12, padding: 14, marginBottom: 10 },
  filterRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginBottom: 8 },
  filterLabel: { fontSize: 10, fontWeight: '700', color: '#555555', textTransform: 'uppercase', letterSpacing: 1, marginTop: 5, minWidth: 40 },
  chipsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, flex: 1 },
  chip: { borderWidth: 1, borderColor: '#2a2a2a', paddingHorizontal: 10, paddingVertical: 3, borderRadius: 20 },
  chipText: { color: '#888888', fontSize: 11 },
  chipActive: { backgroundColor: '#ffffff', borderColor: '#ffffff' },
  chipTextActive: { color: '#000000', fontWeight: '700' },

  // --- SORT BAR ---
  sortBar: { flexDirection: 'row', backgroundColor: '#111111', borderWidth: 1, borderColor: '#222222', borderRadius: 10, padding: 8, gap: 4, marginBottom: 8 },
  sortBtn: { paddingHorizontal: 12, paddingVertical: 5, borderRadius: 20 },
  sortBtnActive: { backgroundColor: '#222222' },
  sortBtnText: { color: '#888888', fontSize: 13, fontWeight: '600' },
  sortBtnTextActive: { color: '#ffffff' },
  resultsCount: { fontSize: 12, color: '#444444', marginBottom: 8 },

  // --- SIDEBAR CARD (shown below feed on mobile) ---
  sideCard: { backgroundColor: '#111111', borderWidth: 1, borderColor: '#1e1e1e', borderRadius: 12, padding: 14, marginBottom: 12 },
  sideTitle: { fontSize: 14, fontWeight: '800', color: '#ffffff', marginBottom: 10 },
  statRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: '#1a1a1a' },
  statLabel: { fontSize: 13, color: '#888888' },
  statVal: { fontSize: 13, fontWeight: '700', color: '#ffffff' },
  trendItem: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: '#1a1a1a' },
  trendRank: { fontSize: 13, fontWeight: '700', color: '#444444', minWidth: 22 },
  trendTitle: { fontSize: 13, fontWeight: '600', color: '#cccccc' },
  trendSub: { fontSize: 11, color: '#555555', marginTop: 1 },

  // --- EMPTY STATE ---
  empty: { alignItems: 'center', justifyContent: 'center', padding: 48, backgroundColor: '#111111', borderWidth: 1, borderColor: '#1e1e1e', borderRadius: 12 },
  emptyIcon: { fontSize: 48, marginBottom: 10 },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: '#ffffff', marginBottom: 4 },
  emptyText: { fontSize: 14, color: '#555555' },

  // --- MODAL ---
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modal: { backgroundColor: '#0d0d0d', borderWidth: 1, borderColor: '#2a2a2a', borderRadius: 16, padding: 28, width: '100%' },
  modalTitle: { fontSize: 20, fontWeight: '800', color: '#ffffff', textAlign: 'center', marginBottom: 14 },
  modalClose: { position: 'absolute', top: 14, right: 14 },
  modalCloseText: { color: '#666666', fontSize: 18 },
  modalSecBtn: { borderWidth: 1, borderColor: '#333333', borderRadius: 24, padding: 12, alignItems: 'center', marginTop: 8 },
  modalSecBtnText: { color: '#ffffff', fontSize: 14, fontWeight: '600' },
  createRow: { flexDirection: 'row', gap: 10 },
  createField: { flex: 1 },
  createLabel: { fontSize: 11, color: '#666666', textTransform: 'uppercase', letterSpacing: 1, fontWeight: '700', marginBottom: 5 },
  picker: { backgroundColor: '#111111', borderWidth: 1, borderColor: '#333333', borderRadius: 8, color: '#ffffff', marginBottom: 10 },

  // --- DETAIL PAGE ---
  backBtn: { borderWidth: 1, borderColor: '#2a2a2a', borderRadius: 8, paddingHorizontal: 14, paddingVertical: 8, alignSelf: 'flex-start', marginBottom: 16 },
  backBtnText: { color: '#888888', fontSize: 14 },
  detailHero: { flexDirection: 'row', gap: 16, backgroundColor: '#111111', borderWidth: 1, borderColor: '#1e1e1e', borderRadius: 12, padding: 18, marginBottom: 12 },
  detailThumb: { width: 90, height: 90, backgroundColor: '#1a1a1a', borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  detailThumbText: { fontSize: 52 },
  detailTitle: { fontSize: 22, fontWeight: '900', color: '#ffffff', marginBottom: 6 },
  detailSection: { backgroundColor: '#111111', borderWidth: 1, borderColor: '#1e1e1e', borderRadius: 12, padding: 16, marginBottom: 12 },
  sectionTitle: { fontSize: 14, fontWeight: '800', color: '#ffffff', borderBottomWidth: 1, borderBottomColor: '#1e1e1e', paddingBottom: 8, marginBottom: 12 },
  detailBody: { fontSize: 14, color: '#888888', lineHeight: 24 },
  updateCard: { backgroundColor: '#1a1a1a', borderWidth: 1, borderColor: '#222222', borderRadius: 10, padding: 12, marginBottom: 8 },
  updateTop: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 },
  updateTitle: { fontSize: 14, fontWeight: '700', color: '#ffffff' },
  updateDate: { fontSize: 11, color: '#555555' },
  updateBody: { fontSize: 13, color: '#888888', lineHeight: 18 },
  commentInput: { backgroundColor: '#1a1a1a', borderWidth: 1, borderColor: '#2a2a2a', borderRadius: 8, color: '#ffffff', fontSize: 14, padding: 12, minHeight: 70, textAlignVertical: 'top', marginBottom: 8 },
  commentCard: { backgroundColor: '#1a1a1a', borderWidth: 1, borderColor: '#222222', borderRadius: 10, padding: 12, marginBottom: 8 },
  commentTop: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 },
  commentUser: { fontSize: 13, fontWeight: '700', color: '#ffffff' },
  commentTime: { fontSize: 11, color: '#444444' },
  commentText: { fontSize: 13, color: '#888888', lineHeight: 18 },

  // --- DEV PROFILE ---
  devHero: { flexDirection: 'row', gap: 16, backgroundColor: '#111111', borderWidth: 1, borderColor: '#1e1e1e', borderRadius: 12, padding: 20, marginBottom: 12 },
  devAvatar: { width: 90, height: 90, backgroundColor: '#1a1a1a', borderRadius: 45, alignItems: 'center', justifyContent: 'center' },
  devAvatarText: { fontSize: 44 },
  devName: { fontSize: 22, fontWeight: '900', color: '#ffffff', marginBottom: 6 },
  devBio: { fontSize: 13, color: '#888888', lineHeight: 20, marginBottom: 8 },
  devStats: { flexDirection: 'row', gap: 20, marginBottom: 10 },
  devStatNum: { fontSize: 18, fontWeight: '900', color: '#ffffff' },
  devStatLabel: { fontSize: 11, color: '#555555', textTransform: 'uppercase', letterSpacing: 0.5 },
  devActions: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  followBtn: { paddingHorizontal: 20, paddingVertical: 8, borderRadius: 20, backgroundColor: '#ffffff' },
  followBtnFollowed: { backgroundColor: 'transparent', borderWidth: 1, borderColor: '#444444' },
  followBtnText: { color: '#000000', fontWeight: '700', fontSize: 14 },
  followBtnTextFollowed: { color: '#ffffff' },
  socialLink: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, backgroundColor: '#1a1a1a', borderWidth: 1, borderColor: '#333333' },
  socialLinkText: { fontSize: 12, fontWeight: '600' },
  devGameCard: { flexDirection: 'row', gap: 14, backgroundColor: '#1a1a1a', borderWidth: 1, borderColor: '#222222', borderRadius: 10, padding: 14, marginBottom: 10 },
  devGameThumb: { width: 60, height: 60, backgroundColor: '#111111', borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  devGameThumbText: { fontSize: 32 },
  devGameTitle: { fontSize: 15, fontWeight: '800', color: '#ffffff', marginBottom: 3 },
  devGameDesc: { fontSize: 12, color: '#888888', lineHeight: 17, marginBottom: 5 },
  devGameMeta: { flexDirection: 'row', gap: 14 },
  devGameMetaText: { fontSize: 11, color: '#555555' },

  // --- DROPDOWN (Modal-based on mobile) ---
  dropdownOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)' },
  dropdownBox: { position: 'absolute', top: 62, backgroundColor: '#111111', borderWidth: 1, borderColor: '#2a2a2a', borderRadius: 12, minWidth: 280, overflow: 'hidden', shadowColor: '#000', shadowOpacity: 0.6, shadowRadius: 16 },
  dropdownHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 14, borderBottomWidth: 1, borderBottomColor: '#222222' },
  dropdownHeaderText: { fontSize: 14, fontWeight: '700', color: '#ffffff' },
  dropdownCloseText: { color: '#666666', fontSize: 16 },
  notifItem: { flexDirection: 'row', gap: 10, padding: 13, borderBottomWidth: 1, borderBottomColor: '#1a1a1a' },
  notifText: { fontSize: 13, color: '#cccccc', lineHeight: 18 },
  notifTime: { fontSize: 11, color: '#555555', marginTop: 3 },
  menuItem: { padding: 13, paddingHorizontal: 16 },
  menuItemText: { fontSize: 14, color: '#cccccc' },
  menuItemLogout: { borderTopWidth: 1, borderTopColor: '#222222' },
  menuItemLogoutText: { color: '#ef4444' },
});